# Generated by Django 5.1.4 on 2025-01-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
